name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - pub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate deployment package
      run: |
        zip -r deploy.zip . -x "*/node_modules/*" "*/dist/*" "*/build/*" "*/coverage/*" "*.git*"

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.EB_APPLICATION_NAME }}
        environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
        version_label: ${{ github.sha }}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy.zip
        use_existing_version_if_available: true
        wait_for_deployment: true
        wait_for_environment_recovery: 60