name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - pub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm run install:all

    - name: Build application
      run: npm run build
      env:
        CI: false  # This prevents treating warnings as errors in create-react-app builds

    - name: Create deployment package
      run: npm run package

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Writ99.2
        environment_name: Writ992-env
        version_label: ${{ github.sha }}
        region: us-west-1
        deployment_package: deploy.tar.gz